---
- name: Run Maven Build
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: clone respository
      git:
        repo: https://github.com/turrence/ansible-mvn-ci.git
        dest: /home/labsuser/ansible-mvn-ci
        clone: yes
        update: yes

    - name: Install Maven
      apt:  
        name: maven
        state: present

    - name: Execute Maven Command
      shell: mvn clean install
      args:
        chdir: /home/labsuser/ansible-mvn-ci
      register: mvn_output
    
    - name: Setup tomcat server
      import_playbook: tomcat-server.yml

    - name: Copy .war file to Tomcat webapps directory
      copy:
        src: /home/labsuser/ansible-mvn-ci/target/hello-world-1.0.war
        dest: /opt/tomcat9/webapps/