---
- name: Run Maven Build
  hosts: all
  become: yes
  become_user: root
  gather_facts: false
  tasks:
    - include_role:
        name: tomcat
    - name: Clone Git Repository
      git:
        repo: 'https://github.com/turrence/ansible-mvn-ci.git'
        dest: '~/helloJava'

    - name: Run Maven Build
      command: mvn clean install
      args:
        chdir: '~/helloJava'