---
- name: Run Maven Build
  hosts: localhost
  tasks:
     - name: Execute Maven Command
       shell: mvn clean install
       args:
         chdir: ./target/
       register: mvn_output

     - name: Display Maven Output
       debug:
         var: mvn_output.stdout_lines