---
- name: Run Maven Build
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: clone respository
      git:
        repo: https://github.com/turrence/ansible-mvn-ci.git
        dest: ~/ansible-mvn-ci
        clone: yes
        update: yes

    - name: Install Maven
      apt:  
        name: maven
        state: present
        update_cache: yes

    - name: Execute Maven Command
      shell: mvn clean install
      args:
        chdir: ~/ansible-mvn-ci
      register: mvn_output
